# Generated by Django 5.0 on 2023-12-29 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import AnonymousUser

class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(default=AnonymousUser(), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=AnonymousUser(), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
